-- local s = require('lib.sessions')

--
-- local buffers = vim.api.nvim_list_bufs()
-- for _, buf in ipairs(buffers) do
-- 	if vim.api.nvim_buf_is_loaded(buf) then
-- 		local filepath = vim.api.nvim_buf_get_name(buf)
-- 		print(s.get_filetype(buf), s.not_term(buf), filepath ~= "", s.not_term(buf) and filepath ~= "")
-- 	end
-- end
--
--
-- local function load_current_line_as_macro(register)
--     register = register or "a"
--     local line = vim.api.nvim_get_current_line()
--     vim.fn.setreg(register, line)
--     print(string.format("Macro loaded into register '%s': %s", register, line))
-- end
--
-- local function paste_current_macro(register)
--     register = register or "a"
--     local macro = vim.fn.getreg(register)
--     if macro == "" then
--         print(string.format("Register '%s' is empty.", register))
--         return
--     end
--     -- vim.api.nvim_feedkeys(macro, "n", false)
--     print(string.format("Pasted macro from register '%s': %s", register, macro))
-- end 
--
--
-- paste_current_macro()


